// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXidDyTDWXSoM0qwyuCqttsNob9hpCpP4',
    appId: '1:1090334684360:web:fb755b53e5e365b781a1fd',
    messagingSenderId: '1090334684360',
    projectId: 'blooddonationapp-71bbc',
    authDomain: 'blooddonationapp-71bbc.firebaseapp.com',
    storageBucket: 'blooddonationapp-71bbc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEpLxUQL4yUCtCocfsRVXHJXRE9VEtG9o',
    appId: '1:1090334684360:android:6b0cac8816b2496a81a1fd',
    messagingSenderId: '1090334684360',
    projectId: 'blooddonationapp-71bbc',
    storageBucket: 'blooddonationapp-71bbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU24cqHqq11xG9z2zji6MFUPKOjfvYIy0',
    appId: '1:1090334684360:ios:de44156bd1ea8f9d81a1fd',
    messagingSenderId: '1090334684360',
    projectId: 'blooddonationapp-71bbc',
    storageBucket: 'blooddonationapp-71bbc.appspot.com',
    iosClientId:
        '1090334684360-8olvd9g794e0a4vke4dnh1m5tblo4acd.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodDonationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU24cqHqq11xG9z2zji6MFUPKOjfvYIy0',
    appId: '1:1090334684360:ios:de44156bd1ea8f9d81a1fd',
    messagingSenderId: '1090334684360',
    projectId: 'blooddonationapp-71bbc',
    storageBucket: 'blooddonationapp-71bbc.appspot.com',
    iosClientId:
        '1090334684360-8olvd9g794e0a4vke4dnh1m5tblo4acd.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodDonationApp',
  );
}
